## SPDX-License-Identifier: GPL-2.0-only

bootblock-y += bootblock.c
romstage-y += cbmem.c
romstage-y += romstage.c
romstage-y += istep89.c
romstage-y += istep810.c
romstage-y += ../../../cpu/power/power9/scom.c
