/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef SOC_ISTEP8_H
#define SOC_ISTEP8_H

enum FABRIC_ASYNC_MODE
{
	FABRIC_ASYNC_PERFORMANCE_MODE = 0x0,
	FABRIC_ASYNC_SAFE_MODE = 0x1,
};

enum FABRIC_CORE_FLOOR_RATIO
{
	FABRIC_CORE_FLOOR_RATIO_RATIO_8_8 = 0x0,
	FABRIC_CORE_FLOOR_RATIO_RATIO_7_8 = 0x1,
	FABRIC_CORE_FLOOR_RATIO_RATIO_6_8 = 0x2,
	FABRIC_CORE_FLOOR_RATIO_RATIO_5_8 = 0x3,
	FABRIC_CORE_FLOOR_RATIO_RATIO_4_8 = 0x4,
	FABRIC_CORE_FLOOR_RATIO_RATIO_2_8 = 0x5,
};

enum FABRIC_CORE_CEILING_RATIO
{
    FABRIC_CORE_CEILING_RATIO_RATIO_8_8 = 0x0,
    FABRIC_CORE_CEILING_RATIO_RATIO_7_8 = 0x1,
    FABRIC_CORE_CEILING_RATIO_RATIO_6_8 = 0x2,
    FABRIC_CORE_CEILING_RATIO_RATIO_5_8 = 0x3,
    FABRIC_CORE_CEILING_RATIO_RATIO_4_8 = 0x4,
    FABRIC_CORE_CEILING_RATIO_RATIO_2_8 = 0x5,
};

#define EPSILON_MIN_VALUE 0x1;
#define EPSILON_MAX_VALUE 0xFFFFFFFF;

#define NUM_EPSILON_READ_TIERS 3;
#define NUM_EPSILON_WRITE_TIERS 2;

#define CHIP_IS_NODE	0x01
#define CHIP_IS_GROUP	0x02

/* From src/import/chips/p9/procedures/xml/attribute_info/nest_attributes.xml */
#define EPS_TYPE_LE	0x01
#define EPS_TYPE_HE	0x02
#define EPS_TYPE_HE_F8	0x03

#endif